### ISSUE TITLE
Identifier replacement should be stricter

### ISSUE THREAD

**Issue by Justineo** [ben-eb/postcss-merge-idents#3]
Current logic doesn't try to identify `animation-name` at all and instead it just match values against some regex.

```css
@keyframes reverse {
    from { opacity: 1; }
    to   { opacity: 0; }
}
@keyframes fadeOut {
    from { opacity: 1; }
    to   { opacity: 0; }
}
.fade {
    animation-direction: reverse;
}
```

Produces:

```css
@keyframes fadeOut {
    from { opacity: 1; }
    to   { opacity: 0; }
}
.fade {
    animation-direction: fadeOut;
}
```

**Comment by ben-eb** [comment]
The module uses regexes for property name checking, not identifier checking. I'm not sure why this is an issue as it is what this module is meant to achieve. The name is irrelevant given that it is further compressed by postcss-reduce-idents.

**Comment by Justineo** [comment]
Hi,

My bad, regexes now have nothing to do with values.

I think this plugin meant to replace `animation-name` in `animation` and `animation-name` itself after merging identical `@keyframes` or `@counter-style`. But `/animation/` will actually match `animation-*`, which will incorrectly replace other animation-related property values if the identifier of a `@keyframes` is the same as a CSS keyword for another property. In the example I gave, `animation-direction` is wrongly set to `fadeOut`.

And even in `animation` property itself, when I have an `animation-name` with the same value as a valid keyword for another property, like `linear`, the result will also go wrong:

```css
@keyframes linear {
    from { opacity: 1; }
    to   { opacity: 0; }
}
@keyframes fadeOut {
    from { opacity: 1; }
    to   { opacity: 0; }
}
.fade {
    animation: 1s linear linear;
}
```

Produces:

```css
@keyframes fadeOut {
    from { opacity: 1; }
    to   { opacity: 0; }
}
.fade {
    animation: 1s fadeOut fadeOut;
}
```

This is because we don't actually parse the `animation` value, and know the first `linear` is an identifier of `@keyframes` while the second one is a keyword for `animation-timing-function`.

**Comment by ben-eb** [comment]
Right, sorry I missed the `direction` part of the original question.

Pull requests always welcome. 👍

**Comment by burdiuz** [comment]
Hi!
While using `gulp-cssnano` I've encountered this error
```
D:\project-path\node_modules\postcss-merge-idents\dist\index.js:21
        if ((0, _has2.default)(obj, key) && obj[key] !== key) {
                              ^
RangeError: Maximum call stack size exceeded
    at Array.hasOwnProperty (native)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:21:31)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
    at recurse (D:\project-path\node_modules\postcss-merge-idents\dist\index.js:22:20)
```
And it appears this happens because of CSS keyframe animation rules
```css
.nc-spin {
  -webkit-animation: nc-spin 2s infinite linear;
          animation: nc-spin 2s infinite linear; }

@-webkit-keyframes nc-spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg); }
  100% {
    -webkit-transform: rotate(359deg);
            transform: rotate(359deg); } }

@keyframes nc-spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg); }
  100% {
    -webkit-transform: rotate(359deg);
            transform: rotate(359deg); } }


.fa-spin {
  -webkit-animation: fa-spin 2s infinite linear;
  animation: fa-spin 2s infinite linear;
}
.fa-pulse {
  -webkit-animation: fa-spin 1s infinite steps(8);
  animation: fa-spin 1s infinite steps(8);
}
@-webkit-keyframes fa-spin {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}
@keyframes fa-spin {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}
```
the recursion goes around `nc-spin`  and `fa-spin` keys. "@keyframes fa-spin" block repeated couple times through resulting CSS file and removing duplicates fixes issue. Not sure if this relevant.
