### ISSUE TITLE
@media & @supports

### ISSUE THREAD

**Issue by Justineo** [ben-eb/postcss-merge-idents#4]
Browsers actually support setting different rules for `@keyframes` with same identifiers according to `@media` and `@supports`.

eg. http://jsbin.com/zicoyebira/edit?html,css,output

Input:

```css
@keyframes spin {
    from { transform: rotate(0deg); }
    to   { transform: rotate(360deg); }
}

@media (max-width: 400px) {
    @keyframes spin {
        from { transform: rotate(0deg); }
        to   { transform: rotate(360deg); }
    }
}

.spin {
    animation: 1s spin infinite linear;
}
```

Produces:

```css
@media (max-width: 400px) {
    @keyframes spin {
        from { transform: rotate(0deg); }
        to   { transform: rotate(360deg); }
    }
}

.spin {
    animation: 1s spin infinite linear;
}
```

Boxes won't spin on wide displays now.
